### ISSUE TITLE
Select ALL Repositories by default

### ISSUE THREAD

**Issue by matthiaslischka** [ostreifel/vsts-contributions#10]
First of all, nice plugin. Thx!

Right now the default selected Repository is always the same and in my case one where I have zero commits. Would be nice if the default behavior would be to filter for all available repositories or support multi select.

BR Matthias

**Comment by ostreifel** [comment]
This is intentional b/c the number of repositories on some accounts is very large and I do not want to spam a ton of repository requests when that is the case.

**Comment by ostreifel** [comment]
If you want the default be all set a bookmark to a filter with all repositories selected.
