### ISSUE TITLE
Dashboard stops updating after multiple repositories are selected

### ISSUE THREAD

**Issue by josecomboni** [ostreifel/vsts-contributions#16]
Playing with this collaboration graph tool, I found that when selecting multiple people and multiple reports, after the about the 5th update, the numbers stop updating. This happened as I was playing with the tool a few minutes after I installed it into our VSTS account.

**Comment by ostreifel** [comment]
Did you get a error in the dev console (f12)?
Are there requests timing out?
Is this purely a function of how many people are requested or is there a specific graph that has data that causes the problem?

**Comment by ostreifel** [comment]
Please reopen if you find more information about this issue.
