### ISSUE TITLE
[Feature Request] Combined graph for all contributions within team

### ISSUE THREAD

**Issue by joeskeen** [ostreifel/vsts-contributions#18]
It's great that you can add all members of your team and display each person individually, but it would be really cool if you could create a single graph that shows all team members' contributions over time.  It would look nice on a team dashboard in VSTS if we could embed it somehow.

**Comment by pabrams** [comment]
It wouldn't look very good, unless you came up with some different color scheme.  The color wraps around from dark back to light after only seven or eight contributions on a single day.
