### ISSUE TITLE
Repository filter is not applied to additional users

### ISSUE THREAD

**Issue by JayCallas** [ostreifel/vsts-contributions#19]
When I navigate to the **Contributions Graph** view, I am shown myself by default and the current Repository is selected. (In my case I am looking at a repository that was just created in late May/early June.)

As I add additional members of the team to the view, their data seems to be collected for **all** repositories since I see data going back the **entire year**.

If there is only a single Repository filter for the page, then all users should be honoring it.

![image](https://user-images.githubusercontent.com/15733663/44924046-15b7fd80-ad18-11e8-87d8-2db37fdb0e81.png)

**Comment by ostreifel** [comment]
Repo refers to version control artifacts: commits, prs, etc. The filter shown includes work items which are not effected by the repository choice.

![image](https://user-images.githubusercontent.com/5203542/44927315-02e9fc80-ad09-11e8-8e7f-cb3d9ab793fc.png)


The project of the page context is the project where the work items are queried from.
![image](https://user-images.githubusercontent.com/5203542/44927511-a20ef400-ad09-11e8-9de1-27f1d14cef24.png)
