### ISSUE TITLE
TFS-2018 WorkItem Contribution Link not working

### ISSUE THREAD

**Issue by jayendranarumugam** [ostreifel/vsts-contributions#21]
Hi,
I just install this Extension, While filtering with the **Created work items**

![capture](https://user-images.githubusercontent.com/25414541/46900610-81b68580-cec2-11e8-9ec3-b6da8676b93c.PNG)

While clicking the contribution Link. It navigates to that particlar Workitem. I get the below error while navigating to the new workitem

![capture](https://user-images.githubusercontent.com/25414541/46900641-f4276580-cec2-11e8-809b-076a635f55d8.PNG)

> **TF400893: Unable to contact the server. This is most likely caused by a network error. Please check your connection and try again.**

If I copy the link and browse it in another tab. It is working fine.

I think this is due to some Authentication issue ?

**Comment by ostreifel** [comment]
This should be fixed now, in the latest version. Please verify.

**Comment by jayendranarumugam** [comment]
Yes, it's working now. Thanks for the quick fix @ostreifel
