### ISSUE TITLE
Activity Filter keeps resetting

### ISSUE THREAD

**Issue by philcart** [ostreifel/vsts-contributions#22]
Windows 10 - 1809.17754.1
Microsoft Edge 44.17754.1.0
TFS 2018 (Tfs2018.Update2) on-premises

After selecting multiple users and/or changing any of the activity filtering options if I reload the page all the selected filtering options revert back to their defaults

![contributions_changed](https://user-images.githubusercontent.com/4084083/47186081-203b5e80-d37b-11e8-95a4-f6396d1ccaf5.png)

![contributions_reset](https://user-images.githubusercontent.com/4084083/47186083-20d3f500-d37b-11e8-8fc2-4dca35e79f88.png)

**Comment by danielheddelin** [comment]
Would be great if updates to the filters also updated the URI to the Contributions Graph, and hence 'saved' the updates.

**Comment by souchprod** [comment]
+1, i can't figure out how to persist the filters, thanks

**Comment by pabrams** [comment]
There is no persistence, but you can copy the link from the address bar, once your filter is ready, and then save that link to a dashboard or something.
