### ISSUE TITLE
Question - How do you place this on Dashboard?

### ISSUE THREAD

**Issue by VaclavElias** [ostreifel/vsts-contributions#23]

**Comment by stedelen** [comment]
@ostreifel what determines how the shading of the contribution tiles?

**Comment by GrzePie** [comment]
!Up! We are having the same issue - were you able to sort it out? :)

**Comment by VaclavElias** [comment]
Nope, I don't think it is that easy.

**Comment by EulerFaria** [comment]
Having the same issue here

**Comment by pabrams** [comment]
It doesn't look like you can put it directly on the dashboard - Iframe widget doesn't render it.  However, you can easily add the link on a markdown widget.  In fact, you pretty much have to do that, unless you want to reconfigure the filters every time you visit the contributions page.
