### ISSUE TITLE
Why is Work Item Write Permission required ?

### ISSUE THREAD

**Issue by babin93** [ostreifel/vsts-contributions#27]
I would like to install that extension on my organization, but I don't think I will be able to go through our internal company security audits with it requiring write permissions.

**Comment by stedelen** [comment]
@babin93 Where did you see requirement for the write permissions, in the repo iteself?

**Comment by babin93** [comment]
Hi, it is actually when installing from the Market Place that the write permissions are asked. I should probably have asked that question in the Market Place.

**Comment by stedelen** [comment]
@babin93 I am not sure why it is mentioned.  I would keep the question open here and in the marketplace too for @ostreifel to review and comment on.

I see this included in this repository scope, but not sure why...

$ grep -B20 -nire vso.work_write                                                                                                                                                                                                                                                vss-extension.json-1-{                                                                                                                                                                                                                                                          vss-extension.json-2-    "manifestVersion": 1,                                                                                                                                                                                                                                  vss-extension.json-3-    "id": "contributions",                                                                                                                                                                                                                                 vss-extension.json-4-    "version": "2.1.18",                                                                                                                                                                                                                                   vss-extension.json-5-    "name": "Contributions Graph",                                                                                                                                                                                                                         vss-extension.json-6-    "scopes": [                                                                                                                                                                                                                                            vss-extension.json-7-        "vso.work",                                                                                                                                                                                                                                        vss-extension.json:8:        "vso.work_write",
--

**Comment by ostreifel** [comment]
It should be fixed now. The reason it was there in the first place was that it is part of the template extension I used as a starting point. The reason it wasn't removed before is that changing the permissions of an extension - even if to reduce - causes all installations to require a re-authorization from an adminstrator on the account to update.
![image](https://user-images.githubusercontent.com/5203542/57181406-1aedbf00-6e48-11e9-8afa-8e23a7a68731.png)

![image](https://user-images.githubusercontent.com/5203542/57181376-aadf3900-6e47-11e9-8a4d-6690b46b7bfd.png)

**Comment by babin93** [comment]
Great ! Thank you very much !
