### ISSUE TITLE
Please include instructions on how to get to the widget

### ISSUE THREAD

**Issue by bbarman4u** [ostreifel/vsts-contributions#28]
Please include instructions on how to get to the widget or view the contributions graph in the new AzureDevOps view? The screenshots are from the old view and also does not include steps on how and where to navigate or view the widget after installing the extension.

**Comment by bbarman4u** [comment]
Ok figured out its inside the Azure boards section -> Contributions Graph

**Comment by mmulhearn** [comment]
agreed, doco needs to better explain where this is

**Comment by httran13** [comment]
thankful for this issue, i found where to find this tool, shouldn't have to be this way lol
