### ISSUE TITLE
Commit user is not identified as AzureDevops user

### ISSUE THREAD

**Issue by luigisaggese** [ostreifel/vsts-contributions#31]
Hello,
I have this issue on contributions graph. Work item are reported under one user and commit under another one. 

![Screen Shot 2019-07-04 at 11 02 48 AM](https://user-images.githubusercontent.com/1014210/60653974-5eb27400-9e4b-11e9-9fdf-31ad9c011d7e.png)
![Screen Shot 2019-07-04 at 11 03 07 AM](https://user-images.githubusercontent.com/1014210/60653973-5eb27400-9e4b-11e9-9fa2-da579a4d3c42.png)

**Comment by stedelen** [comment]
@luigisaggese The activity filters for work items (Created, Reactivated, Closed), are not enabled based on your screen capture.  

True I see the missing commit from 6/19 for Kimyonok. @ostreifel would this be related to the identity lookup (since there are 0 contributions)?

**Comment by luigisaggese** [comment]
@ostreifel @stedelen Yes also in my opinion looks something related to identity lookup.
