### ISSUE TITLE
Question, How can I add the Widget in Azure DevOps

### ISSUE THREAD

**Issue by megel** [ostreifel/vsts-contributions#32]
Where do I find the widget, to add it at the dashboard? Is there a install.md for **Azure DevOps**?

![image](https://user-images.githubusercontent.com/15800069/63122152-53a04700-bfa6-11e9-96bb-7a34fc949652.png)

It's correct installed:
![image](https://user-images.githubusercontent.com/15800069/63122201-6dda2500-bfa6-11e9-8374-3e9a6801cb75.png)

**Comment by stedelen** [comment]
@megel This extension isn't a widget for the dashboard.  It rolls-up under Azure Boards (Boards hub)... This screen capture should help.

![image](https://user-images.githubusercontent.com/33693162/63136098-60b93800-bf9e-11e9-861a-68a1ce3637ab.png)

**Comment by megel** [comment]
Thx!
