### ISSUE TITLE
Is there a way to get a data export of this info (based on what is selected)?

### ISSUE THREAD

**Issue by philcarbone** [ostreifel/vsts-contributions#33]

**Comment by stedelen** [comment]
@philcarbone I do not believe that feature is available with this extension. @ostreifel any comment on if this export could be added?

**Comment by philcarbone** [comment]
friendly poke

**Comment by stedelen** [comment]
@ostreifel is there a way you can add this as a feature enhancement for this extension?

**Comment by ostreifel** [comment]
Sure, if you submit a pull request for adding a download button to the graphs I'll approve it.

Button would be here
![image](https://user-images.githubusercontent.com/5203542/68738137-c66b8f00-05a2-11ea-9b79-9a6f6cc551eb.png)

Code would be added here:
https://github.com/ostreifel/vsts-contributions/blob/01dfb9f75e1b1cbf442eecbca3f16c256a20dcbd/scripts/controls/timeWindow/timeWindow.tsx#L45

Getting started info:
https://github.com/ostreifel/vsts-contributions#getting-started
