### ISSUE TITLE
Add Shortcut for All Repositories and All Individuals

### ISSUE THREAD

**Issue by jeremiahhoyle** [ostreifel/vsts-contributions#34]
As a manager, I want to see my developers contributions across repositories. I would like an easy option to add "All the Repositories" and "All the People in a Group"

**Comment by RaghavendraS05** [comment]
This is a key capability to know the activities done by team members. its like consolidation of Activity feed done by team members.

**Comment by forkisbroke** [comment]
This would be a great feature! A single click to view contributions aggregated by team or subset of specific individuals in a team.

**Comment by ddefoe** [comment]
Totally agree. We use this tool every day (thank you!) but would prefer to just choose "All the Repos" so it is easy to see what someone did in that range across all repos.

**Comment by feralmarmot** [comment]
We also need this ability. Just showing mine, and from only one code repository isn't something I'd ever look at. I need to see my staff's contributions across all of the code repositories and projects.

Currently my use case is open the Contributions Graph page, expand Activity Filters, select everything and everyone, then I look at the charts. Would love to get rid of the config step and just open it up and look at the charts.

**Comment by jerone** [comment]
Agree. Luckily it is creating an sharable link that will prefill your selection again.
