### ISSUE TITLE
[Feature Request] Add the ability to query pull request review to the graph

### ISSUE THREAD

**Issue by sledoux** [ostreifel/vsts-contributions#35]
It would be nice to have a slider for PR reviews. We can define "PR reviews" as the number of pull request you put a status on (Approve/Approve with suggestions/Reject). This wouldn't make much difference on the graph since the number will be relatively small. But you could compare it to the number of pull requests you make. And it could be looked at individually as a statistic. Our team would really love to have this ability.

I'm willing to contribute and do this feature if that's fine.

**Comment by ostreifel** [comment]
Sure,

The main files you will need to look at will be 

https://github.com/ostreifel/vsts-contributions/blob/fc4620f733d7d8c70bc89f4f75d45be1f959e369/scripts/controls/filters.tsx#L73
https://github.com/ostreifel/vsts-contributions/blob/master/scripts/filter.ts#L6
To update the filter ui

https://github.com/ostreifel/vsts-contributions/blob/master/scripts/data/provider.ts#L30
To add a new provider for the data

https://github.com/ostreifel/vsts-contributions/blob/master/scripts/data/git/pullrequests.ts
To get the data

**Comment by sledoux** [comment]
@ostreifel Thanks for the pointers. I tried running the solution in VSCode this afternoon and got a bunch of errors while npm installing. All related to node-sass, any clue how to solve this or did you encounter this problem before?

**Comment by ostreifel** [comment]
![image](https://user-images.githubusercontent.com/5203542/65825426-9f900e00-e22b-11e9-99e9-9d15bf2126fe.png)
The time window and ui will need to be updated too. In the above screen shot I have 2 pull requests reviewed but they don't show up in description below b/c of that.

The files for this are 
https://github.com/ostreifel/vsts-contributions/blob/master/scripts/controls/timeWindow/contributions.tsx#L37
https://github.com/ostreifel/vsts-contributions/blob/master/scripts/controls/timeWindow/timeWindow.tsx
