### ISSUE TITLE
[Feature Request] Support alternative commit emails

### ISSUE THREAD

**Issue by gregmac** [ostreifel/vsts-contributions#38]
When a user commits with different email address than their current identity, the contributions do not appear (or appear as a separate item, which is misleading). What would be nice is to have a way to specify "alternate emails" for a user (eg, like [github does](https://github.com/settings/emails)) so when looking up commits, the primary + alternate emails could be searched and the commit results combined. 

It doesn't appear that Azure DevOps supports the concept of "alternate emails" so I'm not really sure if this would be possible or what the best way would be, so hopefully others that know the API better can chime in.

This would address #30 and #31.

**Comment by K5i4** [comment]
I second this request. I often  run into this issue.

**Comment by surfaace** [comment]
Love to see this implemented because is causing us some tracking issues

**Comment by Alex-ley** [comment]
Would also love to see this
