### ISSUE TITLE
Allow changing person (again)

### ISSUE THREAD

**Issue by darshanrampatel** [ostreifel/vsts-contributions#4]
In a prior version, you could change the person you were looking at and see their contribution history.

In the latest version, this seems to be limited - I think you made this change here:

https://github.com/ostreifel/vsts-contributions/commit/fe979651f47d5e7e087e41be6115fc432b5387f8#diff-e80cbc0a3c45dff2387cac51bf227513R95

Is it possible to add this option back?

**Comment by ostreifel** [comment]
Created special case to allow changing person.

[1.6.7](https://marketplace.visualstudio.com/items?itemName=ottostreifel.contributions)
https://github.com/ostreifel/vsts-contributions/commit/e596c6050a006e11f0ae69228aa3ace5b5c7cdfb

**Comment by darshanrampatel** [comment]
@ostreifel thanks!
