### ISSUE TITLE
Can't change activity filters and can't see contributions

### ISSUE THREAD

**Issue by knockoutpill** [ostreifel/vsts-contributions#40]
**Describe the bug**
I just installed the Contributions Graph so maybe I need to do some configuration of it. If so I can't find where that is though.

However, when I look at my user it says "0 contributions for the year" even though I have committed and pushed lots of stuff.

When I look at the activity filters I can't slide any of the buttons. I want to choose "all projects" but that button is to the left (off), but I can't move any of the sliders/buttons.

I can search for repositories in the repository box in the activity field but I still don't get any data even when choosing a repository that I've done lots of changes in the last few weeks.

**Environment:**
 - Chrome
 - Hosted (Azure Devops)

**Screenshots**
![image](https://user-images.githubusercontent.com/3610569/74730029-b6b8b200-5245-11ea-96a0-53993c5d70d7.png)

**To Reproduce**
1. Go to a repo
2. Click on boards
3. Click on Contributions Graph

**Expected behavior**
I'd like to see my commits being counted in the Contributions Graph.

**Comment by stedelen** [comment]
@knockoutpill Try using the user's email address instead of the identity search via active directory.  There is another open issue related to the identity picker... #26

**Comment by pabrams** [comment]
@knockoutpill It's probably because you have no repositories selected. 
If you're having problems with the buttons, maybe try a different browser.  Edge works for me.  IE probably doesn't work.  If that's not the issue, maybe you need to be a Project Administrator?
