### ISSUE TITLE
Number of comments given by user X for "Reviewed pull request"

### ISSUE THREAD

**Issue by fredrik-hellmangroup** [ostreifel/vsts-contributions#48]
Description:
Would like to see the possibility to track and/or filter on comments for pullrequests. Comments user made regardless if it's their own PR or others.

Feature request:
* Number of comments given by user X for "Reviewed pull request"

Optional request:
* Eliminate duplicate code check-ins (for example, merging same code into different branches)

**Comment by Pxtl** [comment]
Yeah, I've often hand-rolled VSTS API queries for "comments on other developer's PRs" to see which developers are contributing to our pull-request process, even if they're not final approver this is helpful activity information.

**Comment by mbatista** [comment]
I'd love to see that too!

**Comment by jerone** [comment]
Would like to see this kind of information too.

@Pxtl I'm interested in your workaround... do you have any information how and where to build such query?
