### ISSUE TITLE
Only Work Item Contributions are displayed

### ISSUE THREAD

**Issue by suclarke** [ostreifel/vsts-contributions#52]
We installed this extension a while back but haven't really done anything with it until now.

I am trying to view the Contributions graph on a specific, new project and the only thing it is showing me is Work item creation/resolution/closure.

I know there are Commits but it's not picking up anything.

**Environment:**
 - Chrome
 - Azure DevOps cloud

**Screenshots**
![image](https://user-images.githubusercontent.com/69914771/90661529-364c2b80-e23f-11ea-8c57-18de464f10d3.png)

**To Reproduce**
1. Launch Azure DevOps instance and goto Project.
2. Click on Boards - Contribution Graph
3. Add in names of team members to view their contribution
4. Ensure repos are listed
5.  See only Work item related contributions are displayed.

**Comment by feralmarmot** [comment]
I have the same issue. Another dev and I worked on a project all day long. It has 29 commits for me. He has even more than I do but it shows no contribution for the day for him. This is the case all over the place. I can't seem to pin it down to any one thing. It's just randomly counting things as far as I can tell.

**Comment by Pxtl** [comment]
I just noticed we have the same bug.  It's occasionally showing commits, but mostly not.  For example, I can see a smattering of my own commits but cannot view the commits of any other developer.

**Comment by falvarez1** [comment]
Same issue here.  I noticed that if I go to the Contributions page and it lists me automatically then I can see a bunch of contributions, but if I remove myself and then add myself back in then it only lists about 10% of my contributions,
