### ISSUE TITLE
New Users Do Not Show in Activity Filters

### ISSUE THREAD

**Issue by austinjordanFA** [ostreifel/vsts-contributions#54]
**Describe the bug**
New users do not show up in the 'Activity Filters' section. Since I added the extension we have added multiple new staff members but when typing their names they do not show up (ie the auto-complete suggestions). I can not type their names either and get their contributions to show.

**Environment:**
 - Chrome
 - Azure DevOps

**To Reproduce**
1. Install the extension
2. Add a new user to the organization
3. Go to Activity Filters and try and type their name
4. Name does not show up

**Expected behavior**
Typing the person's name shows their suggested name and can choose the user to view their contributions.

**Comment by dannyyy** [comment]
I'm exactly having the same issue. What can I do that other team members appear?
Most of them are registered 9 month, but are not shown.
