### ISSUE TITLE
View all members

### ISSUE THREAD

**Issue by jycouet** [ostreifel/vsts-contributions#6]
Hello, 

Thank you for this plugin, it looks very good :)
Is it possible to see all the team activity? (not using the filter at all?)

Thank you for the info

**Comment by ostreifel** [comment]
I still want this extension to work on larger accounts with lots of users and lots of data without DOSing the account or triggering throttling of the user running the extension. I could try out allowing filtering by team but I think the size limit on a team is very high. Allowing filtering by multiple users with a cap or allowing filtering by teams as long as they aren't too large might work but that would need to be done without adding too much complexity to the ui.
