### ISSUE TITLE
Please allow saving of current filters. 

### ISSUE THREAD

**Issue by nelson-tamayo-zas** [ostreifel/vsts-contributions#62]
Currently, every time you visit the Contributions Graph page you are presented with a sad graph showing a default repository that you may not even do work in.

Most of our team members like to select all of the repositories and modify the other filter options to see a proper contribution.

It would be nice to be able to save these as a view, and even to place them on the dashboard as a widget.

**Comment by rs-mobitech** [comment]
+1 for this feature.  It is very important for me as I keep having to enter data in every time I view contributions.

**Comment by frankshearar** [comment]
The graph filters are stored in the URI - set up the filter the way you want, and bookmark the URI, and you're done. (Specifically, the filter is defined as a URL-encoded JSON blob, like

```json
{
  "identities": [
    {
      "uniqueName": "foo",
      "id": "decafbad-f00d-d00d-baed-9ca642bec5b8",
      "displayName": "Foo",
      "imageUrl": "https://example.com/_api/_common/identityImage?size=2&id=decafbad-f00d-d00d-baed-9ca642bec5b8"
    },
    {
      "uniqueName": "bar",
      "id": "0ff1ce00-f34b-4fdb-867e-540a6b5b4fd4",
      "displayName": "Bar",
      "imageUrl": "https://example.com/_api/_common/identityImage?id=0ff1ce00-f34b-4fdb-867e-540a6b5b4fd4"
    }
  ],
  "allProjects": false,
  "enabledProviders": {
    "Commit": false,
    "CreatePullRequest": true,
    "ClosePullRequest": true,
    "CloseWorkItem": false,
    "CreateWorkItem": false,
    "ResolveWorkItem": false,
    "Changeset": false
  },
  "repositories": [
    {
      "key": "11111111-d982-4db5-b119-8754eb73f0ad",
      "name": "repo1"
    },
    {
      "key": "22222222-6f61-460e-b375-d386549b9a49",
      "name": "repo2"
    }
  ],
  "sharedScale": true
}
```
