### ISSUE TITLE
Contribution graph page loads but does not show any information

### ISSUE THREAD

**Issue by knuthalvor** [ostreifel/vsts-contributions#7]
Installed on premis, TFS 2017 update 2. When loading the page it only shows "Review | Report an Issue" in the upper right corner - no other information is displayed.

Debugging in browser shows a script error on File: contributionsHub.js, Line: 71, Column: 132:
```
Return Q.all([navigationService.getCurrentState(), filter_1.defaultFilter.getValue()]).then(([state, defaultFilter]) => {
	                const [hash] = Object.keys(state);
	                if (hash) {
	                    return parseHashStr(hash);
	                }
	                return defaultFilter;
	            }); 
```
Spesifically on the => line.

Known issue or related to on-premise solution?

**Comment by ostreifel** [comment]
I think this a browser issue specifically and ie issue.

**Comment by ostreifel** [comment]
Patched, IE is now working again
