### ISSUE TITLE
Be able to see completed pull requests across all repositories

### ISSUE THREAD

**Issue by greggbjensen** [ostreifel/vsts-contributions#72]
**Is your feature request related to a problem? Please describe.**
We have a lot of repos on our Team.  I would like to be able to see all pull requests without having to add each one individually.

**Describe the solution that you would like to submit as pull request**
A checkbox to show pull requests across all repositories.  Or, you could also show all when there are no repos in the filter box.

**Comment by vcorr** [comment]
We have the same problem, would be a great feature!

**Comment by francisaguilar21** [comment]
I agree, it's something we also need!

**Comment by ikriz** [comment]
Yeah would like this aswell search across all repositories not just for pull requests but also commits etc
