### ISSUE TITLE
Commit contribution is zero

### ISSUE THREAD

**Issue by RoryNooneV** [ostreifel/vsts-contributions#77]
I see "0 contributions for the year"
for all users, despite recent commits and commits going back years.

Tested in Chrome and Edge
**Screenshots**
![Commits](https://user-images.githubusercontent.com/117017428/198894626-d7131d2b-d32c-41f2-a68c-ca34989e7382.JPG)

Work Items appear fine.

**Comment by gabrielrainha** [comment]
> I see "0 contributions for the year" for all users, despite recent commits and commits going back years.
> 
> Tested in Chrome and Edge **Screenshots** ![Commits](https://user-images.githubusercontent.com/117017428/198894626-d7131d2b-d32c-41f2-a68c-ca34989e7382.JPG)
> 
> Work Items appear fine.

Here the pullrequests and changests ones are also not working. Only work items yields results.
It was working just fine last week.

**Comment by coiouhkc** [comment]
I only have the issue if at least one of the selected repos is archived. Workaround is to remove the archived repo from the list
