### ISSUE TITLE
Is something supposed to happen?

### ISSUE THREAD

**Issue by rwb196884** [ostreifel/vsts-contributions#83]
I see that we have this extension installed in our Azure DevOps, but it doesn't do anything. Is it supposed to?

**Comment by zukilover** [comment]
You can see the Contributions Graph by selecting a Project and then going to Boards > Contributions Graph.

**Comment by anishjoni** [comment]
Similar issue.
I have the extension installed and did go to Project -> Boards, but I don't see the Contributions Graph. Tried refreshing, but still no Contributions Graph.
