### ISSUE TITLE
"Contributions Graph is taking longer than expected to load"

### ISSUE THREAD

**Issue by rlibove** [ostreifel/vsts-contributions#85]
**Describe the bug**
"Contributions Graph" had been working. Now we are getting the error message, "[Contributions Graph](https://marketplace.visualstudio.com/items?itemName=ottostreifel.contributions) is taking longer than expected to load."
This particularly occurs when trying to select user names for the graph.

**Environment:**
 - Chrome
 - hosted (Azure Devops)
 
**Screenshots**
![image](https://github.com/ostreifel/vsts-contributions/assets/111588972/97e39c9f-17a0-460b-9ecc-1af065cb5925)

**To Reproduce**
Navigate to any project. Select the "Contributions Graph" under "Boards". 
Attempt to select users. But the "Suggested People" hangs at "Loading" (Waited 15 minutes and counting)

**Expected behavior**
List of users should appear; Graph should be populated.

**Comment by rabhuwal** [comment]
+1 to the issue. Can this issue be triaged with priority? It's impacting report generation for my team.

**Comment by izah-sm** [comment]
+1 to the same issue. My hopes are that creators (@ostreifel) of Contribution Graph still remembers that they did it (last upgrade was in 2020).

**Comment by GintV** [comment]
+1 to the issue. Last contribution of creator overall was almost 3 years ago... I think someone needs to fork this and start maintaining on their own..
