### ISSUE TITLE
Is there plan on handing over maintenance to someone else ? 

### ISSUE THREAD

**Issue by 12rambau** [ostreifel/vsts-contributions#86]
Nobody pushed to this repository for the past 3 years. I checked @ostreifel profile and he seems to have fly away from GitHub some time ago.... 

Is there someone willing to take over the maintenance burden and release a new version of this super nice extention?

**Comment by conorh-dev** [comment]
I just found it today as well and it is excellent but there are some bits that I would like to improve. 

I don't have the development know how to be able to do this effectively though. One thing I noticed is that when repos are split across multiple projects it is harder to get the overall contribution picture for a user.
