### ISSUE TITLE
Infinite progress indicator when "Resolved work items" is enabled

### ISSUE THREAD

**Issue by jawn** [ostreifel/vsts-contributions#9]
Environment: TFS 2017 update 1.

Everything works as expected, except when "Resolved work items" is enabled. 

![image](https://user-images.githubusercontent.com/1705112/34726921-b04c12a8-f555-11e7-9210-dcf327d73dca.png)

The browser javascript console shows the cause:
The query references a field that does not exist. The error is caused by [Microsoft.VSTS.Common.ResolvedBy]

We are using a custom (XML style) work item process.

**Comment by ostreifel** [comment]
I'm not sure what the expectation is for resolved work items to return when the resolvedBy field has been removed.

The only work around I could see would be to for the extension allow custom queries (with validation) and to remove created, closed and resolved workitems options when their backing fields are not in the process.

In the meantime I can make sure that errors are handled better and stop the spinner

**Comment by jawn** [comment]
> In the meantime I can make sure that errors are handled better and stop the spinner
That sounds good

**Comment by ostreifel** [comment]
updated

**Comment by jawn** [comment]
@ostreifel Do you know if you need to uninstall & reinstall an extension to get the updated version in TFS 2017 update 1? I could not find docs about that.

**Comment by ostreifel** [comment]
The [closest](https://social.msdn.microsoft.com/Forums/vstudio/en-US/f6d64e51-5c1b-4c9b-b783-03fc77dfacfb/tfs-2017-buildrelease-extension-updates?forum=tfsbuild) I could find says it should happen on its own but I haven't tested it myself. 

You may have to reintall.
